// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPttiLNJh52IfvbXzeqNSDN-D1zw_hC1o',
    appId: '1:546856549650:web:d3f6afde6f8d76ba9607cb',
    messagingSenderId: '546856549650',
    projectId: 'unicash-88',
    authDomain: 'unicash-88.firebaseapp.com',
    storageBucket: 'unicash-88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkC1Ie0LIUoHmwLvAVnywBYQNpM7Ys16Y',
    appId: '1:546856549650:android:66c9a08793d77df89607cb',
    messagingSenderId: '546856549650',
    projectId: 'unicash-88',
    storageBucket: 'unicash-88.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJHLXHarq06ieHjxCXDmn-K1qygTsEWEU',
    appId: '1:546856549650:ios:e6328d800c3348449607cb',
    messagingSenderId: '546856549650',
    projectId: 'unicash-88',
    storageBucket: 'unicash-88.firebasestorage.app',
    iosBundleId: 'com.example.unicash',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBghLQ8vNwrnRJLVtT8YxCB9s59GMkQzQg',
    appId: '1:514464288152:ios:212d8215f1bfb3df94efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    storageBucket: 'unicash-8888.firebasestorage.app',
    iosBundleId: 'com.example.unicash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD1JnNtBTGgM6C_O3MD-hHjLFRBE9wyvo',
    appId: '1:514464288152:web:596891222b5efeb294efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    authDomain: 'unicash-8888.firebaseapp.com',
    storageBucket: 'unicash-8888.firebasestorage.app',
  );

}
