// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD1JnNtBTGgM6C_O3MD-hHjLFRBE9wyvo',
    appId: '1:514464288152:web:10891e6db4e56aae94efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    authDomain: 'unicash-8888.firebaseapp.com',
    storageBucket: 'unicash-8888.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjyX0TMnRDsisunpgEdJb1wKOneTme8w',
    appId: '1:514464288152:android:c478f4fac55f52f894efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    storageBucket: 'unicash-8888.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBghLQ8vNwrnRJLVtT8YxCB9s59GMkQzQg',
    appId: '1:514464288152:ios:212d8215f1bfb3df94efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    storageBucket: 'unicash-8888.firebasestorage.app',
    iosBundleId: 'com.example.unicash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBghLQ8vNwrnRJLVtT8YxCB9s59GMkQzQg',
    appId: '1:514464288152:ios:212d8215f1bfb3df94efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    storageBucket: 'unicash-8888.firebasestorage.app',
    iosBundleId: 'com.example.unicash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD1JnNtBTGgM6C_O3MD-hHjLFRBE9wyvo',
    appId: '1:514464288152:web:596891222b5efeb294efed',
    messagingSenderId: '514464288152',
    projectId: 'unicash-8888',
    authDomain: 'unicash-8888.firebaseapp.com',
    storageBucket: 'unicash-8888.firebasestorage.app',
  );

}